name: task_tacker
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.2
  flutter_slidable: ^3.0.0
  lottie: ^2.6.0
  modal_bottom_sheet: ^3.0.0-pre
  # Service
  http: ^1.0.0
  get_it: ^7.6.7
  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2
  # Location
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  # Language
  easy_localization: ^3.0.4
  # Firebase
  firebase_core: ^2.25.4
  firebase_remote_config: ^4.3.13
  # Notifications
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  image_path: "assets/icons/playstore.png"
  image_path_android: "assets/icons/playstore.png"
  image_path_ios: "assets/icons/appstore.png"
  android: true
  ios: true
  
  

flutter:

 
  uses-material-design: true

  
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/translations/

 
  fonts:
    - family: timesbold
      fonts:
        - asset: assets/fonts/times/TimesBoldTr.otf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf  
  

    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf  


    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf


